# GCP Cloud Run Service Configuration for CemAI Control Tower UI
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cemai-infrastructure-ui-dev
  namespace: cemai-dev
  labels:
    app: cemai-ui
    environment: development
    version: v1.0.0
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
      labels:
        app: cemai-ui
        environment: development
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/cemai-project/cemai-infrastructure-ui-dev:latest
        name: cemai-ui
        ports:
        - containerPort: 80
          name: http1
        env:
        - name: API_BASE_URL
          value: "https://api-dev.cemai.com"
        - name: WS_URL
          value: "wss://ws-dev.cemai.com"
        - name: APP_ENV
          value: "development"
        - name: APP_VERSION
          value: "1.0.0-dev"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true

